// Flat config generated by @nuxt/eslint (Nuxt-aware: knows the auto-imports,
// components and route types). Requires `.nuxt` to exist — run `nuxi prepare`,
// `dev`, or `build` first (CI does this before linting).
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt({
  rules: {
    'vue/multi-word-component-names': 'off',
  },
})
